odom2robot_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    print_diagnostics: true
    publish_acceleration: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: gmr/odom
    odom0_config: [true, true, false, # x, y, z
                   false, false, true,  # roll, pitch, yaw
                   false, false, false,   # velx, vely, velz
                   false, false, false, # velroll, velpitch, velyaw
                   false, false, false] # accelx, accely, accelz